name: Greetings

on:
  pull_request_target:
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.AGENDA_TECH_BOT_PAT }}
          issue-message: "Boas vindas e obrigada pela sua contribuição!' first issue"
          pr-message: "Boas vindas e obrigada pela sua contribuição!' first pull request"
